export default [
    {
        "id": "1",
        "projectName": "Night of the Living Dead",
        scenes: [
            {
                "sceneNumber": "1",
                "setting": "EXT.",
                "description": "French countryside",
                "timeOfDay": "DUSK",
                "shortSummary": "Movie starts with zombie eating a man in the woods.",
                "scriptPageStart": "1",
                "scriptPageEnd": "3",
                "lengthInEighths": "2 1/3",
                elements: {
                    animalHandler: [],
                    cast: ["Zombie Sam", "Random Citizen"],
                    extras: [],
                    greenery: ["Forest"],
                    livestock: [],
                    makeupHair: ["Fake blood", "Hairspray"],
                    mechanicalFx: [],
                    miscellanous: [],
                    music: [],
                    opticalFx: [],
                    props: ["Knife"],
                    security: [],
                    setDressing: [],
                    sound: [],
                    specialEquipment: [],
                    specialFx: [],
                    stunts: ["Zombie Sam jumps random citizen."],
                    vehicles: [],
                    visualFx: [],
                    wardrobe: ["Dirty clothes for Zombie"],
                },
            },
        ],
    },
    {
        "id": "2",
        "projectName": "Blade Runner 2049",
        scenes: [
            {
                "sceneNumber": "1",
                "setting": "EXT.",
                "description": "Unknown planet",
                "timeOfDay": "DAY",
                "shortSummary": "Movie starts with Sapper Morton looking for K.",
                "scriptPageStart": "1",
                "scriptPageEnd": "5",
                "lengthInEighths": "5 1/8",
                elements: {
                    animalHandler: [],
                    cast: ["Sapper Morton", "K"],
                    extras: [],
                    greenery: ["Random Plnet"],
                    livestock: [],
                    makeupHair: [],
                    mechanicalFx: [],
                    miscellanous: [],
                    music: [],
                    opticalFx: [],
                    props: ["Gun"],
                    security: [],
                    setDressing: [],
                    sound: [],
                    specialEquipment: [],
                    specialFx: [],
                    stunts: ["Sapper Morton and K's fight."],
                    vehicles: ["K's car"],
                    visualFx: [],
                    wardrobe: ["K's car", "Sapper Morton's car"],
                },
            },
        ],
    },
]